name: EXSimplify
version: '${project.version}'
main: org.luiscodework.exsimplify.EXSimplify
api-version: 1.19
commands:
  fly:
    description: Enables fly to the user who did run it, or the selected target.
    usage: /fly [player]
    aliases: [f]