name: EXSimplify
version: '1.0.0-LoggingDisabled'
main: org.luiscodework.exsimplify.EXSimplify
api-version: 1.19
commands:
  fly:
    description: Enables fly to the user who did run it, or the selected target.
    usage: /fly [player]
    aliases: [f]
  heal:
    description: Heals the user who did run it, or the selected target.
    usage: /heal [player]
    aliases: [h]
permissions:
  exsimplify.fly:
    description: This permission allows users to use the /fly command.
    default: op
    children:
      exsimplify.fly.others: true
  exsimplify.heal:
    description: This permission allows users to use the /heal command.
    default: op
    children:
      exsimplify.heal.others: true
softdepend: [LuckPerms]